# name: lstm
# num_layers: 2
# bidirectional: true
# use_layernorm: true
# num_classes: 1
# hidden_dim: 64
# dropout: 0.756310
# batch_size: 128
# lr: 0.011043
# npy_path: /app/dev/spatial_encoding/data/pse
# res_dir: /app/dev/spatial_encoding/yield_prediction/results_same_data/lstm
# epochs: 60
# patience: 5



name: lstm
num_layers: 4
bidirectional: false
use_layernorm: true
num_classes: 1
hidden_dim: 128
dropout: 0.246091
batch_size: 256
lr: 0.002252
npy_path: /app/dev/spatial_encoding/data/pse
res_dir: /app/dev/spatial_encoding/yield_prediction/results_same_data/lstm2
epochs: 80
patience: 10
