# config.yaml
defaults:
  - model_config: mlp
  - _self_


training:
  optimizer: adam
  seed: 3407
  device: cuda
  num_workers: 8
  display_step: 10


dataset:
  label_path: '/app/dev/spatial_encoding/data/composite_npy/labels.json'
  norm_path: '/app/dev/spatial_encoding/yield_prediction/data_preparation/min_max_L2_U98_hist.json'
  start_doy_idx: 11 
  end_doy_idx: 38
  feature_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 12, 14]
  train_years: [2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]
  test_years_d: [2020]
  test_years_nd: [2021]
  input_dim: 12
  seq_length: 27